<div class="table-responsive">
    
    <h1><?= $this->escapeHtml($this->trad->_("Medicaments")) ?></h1>
    
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>#</th>
            <th><?= $this->escapeHtml($this->trad->_("Name")) ?></th>
            <th><?= $this->escapeHtml($this->trad->_("Picture")) ?></th>
            <th><?= $this->escapeHtml($this->trad->_("Class")) ?></th>
            <th><?= $this->escapeHtml($this->trad->_("Route")) ?></th>
            <th><?= $this->escapeHtml($this->trad->_("DCI")) ?></th>
            <th>Dosage</th>
            <th><?= $this->escapeHtml($this->trad->_("Unity")) ?></th>
            <th></th>
        </tr>
        </thead>
        
        <tbody>
        
            <?php  foreach($this->medicaments as $medoc ){
                
                /**
                 * @var Laminas\View\Renderer\PhpRenderer $this
                 * @var User\Model\Entity\MedicamentEntity $medoc
                 */
                ?>
                <tr>
                    <td><?= $medoc->getMedicamentId(); ?></td>
                    <td><?= $medoc->getName(); ?></td>
                    <td><img src="images/<?= $medoc->getPhoto(); ?>" alt="<?= $medoc->getPhoto(); ?>"></td>
                    <td><?= $medoc->getClasseId(); ?></td>
                    <td><?= $this->trad->_($medoc->getAdministration()); ?></td>
                    <td><?= $medoc->getDci(); ?></td>
                    <td><?= $medoc->getDosage(); ?></td>
                    <td><?= $medoc->getUnite(); ?></td>

                    <td>
                        <a href="<?= $this->url('edit',['id' => $medoc->getMedicamentId() ]) ?>"
                            ><?= $this->trad->_("Edit") ?></a>
                        
                        <a href="<?= $this->url('remove',['id' => $medoc->getMedicamentId() ]) ?>"
                           onclick="return confirm('<?= $this->trad->_("Are you sure ?") ?>')"
                            ><?= $this->trad->_("Delete") ?></a>
                    </td>
                </tr>
            
            <?php } ?>

            <tr>
            <td colspan="8"></td>

            <td>
                <a href="<?= $this->url('add') ?>"
                    ><?= $this->trad->_("Add") ?></a>
            </td>
            </tr>
        
        </tbody>
    </table>
</div>