<?php
  
    $title = $this->translate("Medic form");
    
    $this->headTitle($this->escapeHtml($title));
    
    $this->headMeta()->appendName('keywords',$title);
    $this->headMeta()->appendName('description',$title);
    
    $form = $this->form;
    
    $form->setAttribute('action', $this->url('save'));
    $form->prepare();

?>

<div class="container">
    
    <div class="row">
        <div class="col-md-5 shadow-sm">
            <h3 class="mb-3 pt-2 text-md-center">
                <?= $this->escapeHtml($title) ?>
            </h3>
            
            <?= $this->form()->openTag($form) ?>
    
            <!-- name input field -->
            <div class="mb-3">
                <?= $this->formLabel($form->get('name'))?>
                <div class="form-group"><?= $this->formText($form->get('name'))?></div>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('name'))?></div>
            </div>
    
            <!-- photo input field -->
            <div class="mb-3">
                <?= $this->formLabel($form->get('photo'))?>
                <div class="form-group"><?= $this->formFile($form->get('photo'))?></div>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('photo'))?></div>
                
                <?php if(isset($medicament)){?>

                    <img src="images/<?= $medicament['photo'] ?>" alt="images/<?= $medicament['photo'] ?>">
                    
                <?php } ?>
            </div>
    
            <!-- classe input field -->
            <div class="mb-3">
                <?= $this->formLabel($form->get('classe_id'))?>
                <div class="form-group"><?= $this->formSelect($form->get('classe_id'))?></div>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('classe_id'))?></div>
            </div>
            
            <!-- administration input field -->
            <div class="mb-3">
                <?= $this->formLabel($form->get('administration'))?>
                <div class="form-group"><?= $this->formSelect($form->get('administration'))?></div>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('administration'))?></div>
            </div>
    
            <!-- dosage input field -->
            <div class="mb-3">
                <?= $this->formLabel($form->get('dosage'))?>
                <div class="form-group"><?= $this->formNumber($form->get('dosage'))?></div>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('dosage'))?></div>
            </div>
    
            <!-- unite input field -->
            <div class="mb-3">
                <?= $this->formLabel($form->get('unite'))?>
                <div class="form-group"><?= $this->formNumber($form->get('unite'))?></div>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('unite'))?></div>
            </div>
            
            <!-- CSRF and submit fields -->
            <div class="mb-3 float-right">
                <?= $this->formHidden($form->get('medicament_id')) ;?>
                <?= $this->formHidden($form->get('user_id')) ;?>
                <?= $this->formHidden($form->get('csrf')) ;?>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('csrf'))?></div>
                <div class="form-group"><?= $this->formSubmit($form->get('create_account'))?></div>
            </div>
            
            <?= $this->form()->closeTag($form) ?>
    
        </div>
    </div>
</div>
