<?php
    
    $flash = $this->flashMessenger();
    
    $flash->setMessageOpenFormat(
        '<div %s>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        
        
        <ul class="list-unstyled">
            <li>
        '
    )->setMessageSeparatorString(' </li><li>')
        ->setMessageCLoseString('</li></ul></div>');
    
    echo $flash->render('info',['alert WS-alert','alert-dismissable','alert-info']);
    echo $flash->render('error',['alert WS-alert','alert-dismissable','alert-danger']);
    echo $flash->render('defautl',['alert WS-alert','alert-dismissable','alert-warning']);
    echo $flash->render('success',['alert WS-alert','alert-dismissable','alert-success']);