<?php
    
    $title = $this->translate("Sign in");
    
    $this->headTitle($this->escapeHtml($title));
    
    $this->headMeta()->appendName('keywords',$title);
    $this->headMeta()->appendName('description',$title);
    /**
     *
     */
    $form = $this->form;
    
    /**
     *  @var \User\Form\Auth\LoginForm $form
     * @var Laminas\View\Renderer\PhpRenderer $this
     */
    
    $form->setAttribute('action', $this->url('sign-in'));
    $form->prepare();

?>

<div class="container">
    
    <div class="row">
        <div class="col-md-5 shadow-sm">
            <h3 class="mb-3 pt-2 text-md-center">
                <?= $this->escapeHtml($this->trad->_("Sign In")) ?>
            </h3>
            
            <?= $this->form()->openTag($form) ?>
            
            <span class="form-text text-muted pb-2">
                <?= sprintf( $this->trad->_("Don't have an account yet ? %sJoin here%s"),
                    '<a href="'.$this->url('sign-up').'">',"</a>"
                ) ?>
            </span>
            
            <!-- email input field -->
            <div class="mb-3">
                <?= $this->formLabel($form->get('email'))?>
                <div class="form-group"><?= $this->formEmail($form->get('email'))?></div>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('email'))?></div>
            </div>
            
            <!-- password input field -->
            <div class="mb-3">
                <?= $this->formLabel($form->get('password'))?>
                <div class="form-group"><?= $this->formPassword($form->get('password'))?></div>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('password'))?></div>
            </div>
            
            <!-- remember me input field -->
            <div class="mb-3">
                <div class="custom-control custom-checkbox">
                    <?= $this->formCheckbox($form->get('recall'))?>
                    <?= $this->formLabel($form->get('recall'))?>
                </div>
            </div>
            
            <!-- CSRF and submit fields -->
            <div class="mb-3 float-right">
                <?= $this->formHidden($form->get('csrf')) ;?>
                <div class="text-danger"> <?= $this->formElementErrors($form->get('csrf'))?></div>
                <div class="form-group"><?= $this->formSubmit($form->get('login_account'))?></div>
            </div>
            
            <?= $this->form()->closeTag($form) ?>
        
        </div>
    </div>
</div>
