<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
use User\Translate\TranslateAction;

?>
<?= $this->doctype() ?>
<html lang="<?= TranslateAction::getInstance()->getLocale() ?>">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/app.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <div class="logo col-4 text-center">
                        <a href="<?= $this->url("home" ) ?>" class="btn btn-sm btn-outline-secondary"
                            ><?= TranslateAction::getInstance()->_("Home") ?></a>
                    </div>

                    <div class="col-4 d-flex justify-content-end align-items-center">
        
                        <?php if( $this->Identity() ){?>

                            <a href="<?= $this->url("profile" ) ?>" class="btn btn-sm btn-outline-secondary"
                                ><?= TranslateAction::getInstance()->_("Profile") ?></a>
                            <a href="<?= $this->url("sign-out" ) ?>" class="btn btn-sm btn-outline-secondary"
                                ><?= TranslateAction::getInstance()->_("Quit") ?></a>
        
                        <?php } else { ?>

                            <a href="<?= $this->url("sign-in" ) ?>" class="btn btn-sm btn-outline-secondary"
                                ><?= TranslateAction::getInstance()->_("Login") ?></a>
                            <a href="<?= $this->url("sign-up" ) ?>" class="btn btn-sm btn-outline-secondary"
                                ><?= TranslateAction::getInstance()->_("Join") ?></a>
        
                        <?php } ?>

                    </div>
                    
                    <div class="col-4 justify-content-end align-items-right">
                        
                        <select target="<?= $this->url("set-locale") ?>" id="select_locale">
                            <option <?= TranslateAction::getInstance()->getLocale() =="fr" ? "selected" :"" ?> value="fr">FR</option>
                            <option <?= TranslateAction::getInstance()->getLocale() =="en" ? "selected" :"" ?> value="en">EN</option>
                        </select>
                        
                    </div>
                    
                </div>
            </div>
        </nav>
        
        <main class="container" role="main">
            
            <?= $this->partial('partial/flash.phtml',$this->flashMessenger() ); ?>
            
            <?= $this->content ?>
            <hr>
        </main>
        <footer class="text-center text-muted">
            <div class="small">
                <p class="mb-1">
                    <?= TranslateAction::getInstance()->_("Copyright &copy; ".date('Y')." all rights reserved" ) ?>
                </p>
                
                <a href="https://getlaminas.org/">Laminas Project</a>
            </div>
            
        </footer>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
