<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/app.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">
                                Home <span class="sr-only">(current)</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <div class="container">
            <header class="brand-header py-3">
                <div class="row flex-nowrap justify-content-between align-items-center">
                    <div class="col-4 pt-1">
                        <?= date('l,j F, Y'); ?>
                        
                    </div>
                    
                    <div class="logo col-4 text-center">
                        <a href="<?= $this->url("home" ) ?>" class="btn btn-sm btn-outline-secondary">Home</a>
                    </div>

                    <div class="col-4 d-flex justify-content-end align-items-center">
                    
                <?php if( $this->Identity() ){?>

                         <a href="<?= $this->url("profile" ) ?>" class="btn btn-sm btn-outline-secondary">profile</a>
                         <a href="<?= $this->url("sign-out" ) ?>" class="btn btn-sm btn-outline-secondary">Quit</a>
                 
                <?php } else { ?>
            
                         <a href="<?= $this->url("sign-in" ) ?>" class="btn btn-sm btn-outline-secondary">Login</a>
                         <a href="<?= $this->url("sign-up" ) ?>" class="btn btn-sm btn-outline-secondary">Join</a>
                
                <?php } ?>
                    
                    </div>
                
                </div>
            </header>
            
            <div class="appNav py-1 mb-2">
                <nav class="nav d-flex justify-content-between">
                    <a href="#" class="pt-2 text-muted">Home</a>
                    <a href="#" class="pt-2 text-muted">Members</a>
                </nav>
            </div>
        </div>
        
        <main class="container" role="main">
            
            <?= $this->partial('partial/flash.phtml',$this->flashMessenger() ); ?>
            <?= $this->content ?>
            <hr>
        </main>
        <footer class="text-center text-muted">
            <div class="small">
                <p class="mb-1">
                    <?= $this->translate("Copyright &copy; ".date('Y')." all rights reserved" ) ?>
                </p>
                
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a href="#">Privacy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Terms</a>
                    </li>
                </ul>
                
                <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
            </div>
            
        </footer>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
