<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use User\Translate\TranslateAction;
?>
<div class="jumbotron">
    <h1 class="display-4"><?= TranslateAction::getInstance()->_("Welcome") ?></h1>
</div>

<div class="card-deck">
    <div class="card">
        <div class="card-body">
    
            <?php if( $this->Identity() ){?>

                <a href="<?= $this->url("profile" ) ?>"  class="btn btn-primary"
                    ><?= TranslateAction::getInstance()->_("Profile") ?> &raquo;</a>
    
            <?php } else { ?>

                <a href="<?= $this->url("sign-in" ) ?>" class="btn btn-primary"
                    ><?= TranslateAction::getInstance()->_("Login") ?> &raquo;</a>
    
            <?php } ?>
            
        </div>
    </div>
    

    
    
    <div class="card">
        <div class="card-body">
    
            <?php if( $this->Identity() ){?>

                <a href="<?= $this->url("sign-out" ) ?>" class="btn btn-primary"
                ><?= TranslateAction::getInstance()->_("Quit") ?> &raquo;</a>
    
            <?php } else { ?>

                <a href="<?= $this->url("sign-up" ) ?>"class="btn btn-primary"
                ><?= TranslateAction::getInstance()->_("Join") ?> &raquo;</a>
    
            <?php } ?>

        </div>
    </div>

    <div class="card">
        <h2 class="card-header"><?= TranslateAction::getInstance()->_("Languages") ?> </h2>
        <div class="card-body">
            <p>
            </p>

            <a class="btn btn-primary" href="<?= $this->url("set-locale",["locale" => "fr"] ) ?>" >FR &raquo;</a>
            <a class="btn btn-primary" href="<?= $this->url("set-locale",["locale" => "en"] ) ?>" >EN &raquo;</a>
        </div>
    </div>
</div>
